
export const TRENDINGS_SEARCHED = 'TRENDINGS_SEARCHED'
export const GENRES_SEARCHED = 'GENRES_SEARCHED'
export const MOVIES_BY_GENRE_SEARCHED = 'MOVIES_BY_GENRE_SEARCHED'
export const MOVIE_SEARCHED = 'MOVIE_SEARCHED'
export const MOVIES_FILTERED = 'MOVIES_FILTERED'
